### ISSUE TITLE
Google Maps does not load and breaks the website main functionnalities.

### ISSUE THREAD

**Issue by gabsoftware** [roberdam/Xaddress#12]
I wanted to try your service.
Unfortunately it it does not work at all, Google Maps does not load.

See screenshots below:
http://www.imagebam.com/image/399847499197039
http://www.imagebam.com/image/01d4a7499197040

Tried with 3 different browsers.

**Comment by roberdam** [comment]
Thanks Gabriel, 
It seems that it reached the daily usage limit for google maps in 6 hours!, I enable billing for google maps  and now it should be working again, let me know.

**Comment by gabsoftware** [comment]
Please reopen. Still does not work like yesterday.

http://www.imagebam.com/image/951467499264940

**Comment by roberdam** [comment]
Can you try with http://www.xaddress.org/try?lng=es and let me know please.

**Comment by RyanZim** [comment]
@roberdam Works with `es` for me, same problem with `en`.

**Comment by roberdam** [comment]
Does  http://www.xaddress.org/try?lng=en works for you Ryan?

**Comment by RyanZim** [comment]
@roberdam Yes, it does now, it wasn't earlier.

**Comment by roberdam** [comment]
Great!, it seems to be a problem with the Google maps Api and the bare domain, but it seems to work ok with www.

**Comment by roberdam** [comment]
Let me know if you have again problems using www, in the meanwhile I will close the issue

**Comment by gabsoftware** [comment]
Google maps load now, but when I click the button "Get your XAddress" there is a loading animation, but nothing happens afterwards.

**Comment by roberdam** [comment]
Can you check your console Gabriel, what browser are you using?

**Comment by gabsoftware** [comment]
I don't have a PC right now, I will post a screenshot of the console as soon as possible.

**Comment by roberdam** [comment]
Thanks Gabriel, can you tell me on which country do you want to create a Xaddress and if  you try for example on another country do you have the same issue?

**Comment by gabsoftware** [comment]
France. This week I'm afraid I won't be able to put my hands on a computer (holidays). I will get back with the requested information ASAP.

**Comment by sabas** [comment]
Could you switch to use OpenStreetMap instead of Google Maps?
Are you using some geocoding (apart from that search box in the map) or you're using it only for visualization?

**Comment by roberdam** [comment]
Hi @sabas ,
The main reason to use Google Maps are the satellite photos, so you can find a place even when it does not show on the maps.

**Comment by gabsoftware** [comment]
Still does not work for me. Please reopen. Using Chromium.

Screenshot:
http://www.imagebam.com/image/187fce501103674

Country: France

It works in Paris! But not outside.

**Comment by kostasx** [comment]
Same problem with Athens, Greece.

**Comment by roberdam** [comment]
thanks @kostasx can you try again , it should be fixed now, let me know otherwise

**Comment by kostasx** [comment]
Fine. Works now. Thank you!
